name: zefyrka
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter based on Zefyr package.
version: 1.3.0
homepage: https://github.com/glynskyi/zefyrka

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  iconsax:
    git:
      url: https://github.com/tukaramc/flutter_iconsax1.git
      ref: c4607d3a6cdb439fbd0f340f0db414af28056531

  collection: ^1.16.0
  url_launcher: ^6.1.2
  quill_format: ^1.0.2
  notus_format: ^1.0.3
  characters: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
